services:
  catfinder:
    build: .
    container_name: catfinder_pro
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Santiago
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./captures:/app/captures
      - ./models:/app/models:ro
    shm_size: "512mb"
