cameras:
- name: fuera
  rtsp_url: "CHANGE_ME"
  enabled: true
  detect_fps: null
  cooldown_seconds: null
  max_frame_width: null
  split_mode: none
- name: fuera2
  rtsp_url: "CHANGE_ME"
  enabled: true
  detect_fps: null
  cooldown_seconds: null
  max_frame_width: null
  split_mode: none
- name: patio
  rtsp_url: "CHANGE_ME"
  enabled: true
  detect_fps: null
  cooldown_seconds: null
  max_frame_width: null
  split_mode: top
- name: patio2
  rtsp_url: "CHANGE_ME"
  enabled: true
  detect_fps: null
  cooldown_seconds: null
  max_frame_width: null
  split_mode: bottom
